#%RAML 1.0 Trait

usage:  |
  This trait can be used to apply an Authorization header parameter
  to any resources or HTTP methods using Bearer access token.
headers:
  Authorization:
     description: The API key which is bearer token needs to be passed